# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', jsonfield.fields.JSONField()),
            ],
        ),
    ]
